# Generated by Django 4.1.1 on 2022-10-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('timeStamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
