# Generated by Django 4.1.1 on 2022-10-05 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icode', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
