# Generated by Django 4.1.1 on 2022-10-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icode', '0003_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
